<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>KaLara.Engine</AssemblyName>
    <RootNamespace>KaLara.Engine</RootNamespace>
  </PropertyGroup>
</Project>
